FROM        yapen-docker:base
MAINTAINER  gambler1541@gmail.com

ENV         BUILD_MODE              dev
ENV         DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

# dev용 requirements 설치
COPY        ./requirements.txt /srv/
RUN         pip install -r /srv/requirements.txt

COPY        .   /srv/project
ENV         PROJECT_DIR     /srv/project

#Nginx config
            # nginx.conf(Nginx자체 설정파일)을 덮어씌우기
RUN         cp -f   /srv/project/.config/${BUILD_MODE}/nginx.conf \
                    /etc/nginx/nginx.conf && \

            # available에 nginx_app.conf 파일 복사
            cp -f   /srv/project/.config/${BUILD_MODE}/nginx_app.conf \
                    /etc/nginx/sites-available/ && \
            # 이미 sites-enabled에 있던 모든 내용 삭제
            rm -f   /etc/nginx/sites-enabled/* && \
            # available에 있는 nginx_app.conf를 enabled로 링크
            ln -sf  /etc/nginx/sites-available/nginx_app.conf \
                    /etc/nginx/sites-enabled


RUN         cp -f   srv/project/.config/${BUILD_MODE}/supervisor_app.conf \
                    /etc/supervisor/conf.d/

CMD         supervisord -n

