FROM        python:3.6.5-slim
MAINTAINER  gambler1541@gmail.com

RUN         apt -y update && apt -y dist-upgrade

# 로컬의 requirements.txt 파일을 /srv에 복사 후 pip install 실
COPY        ./requirements.txt /srv/
RUN         pip install -r /srv/requirements.txt