# Generated by Django 2.1 on 2018-08-13 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateTimeField(blank=True)),
                ('checkout_date', models.DateTimeField(blank=True)),
                ('reservation_price', models.IntegerField(blank=True, default=0)),
                ('subscriber', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.CharField(blank=True, max_length=100)),
                ('pickup_or_not', models.BooleanField(blank=True, default=True)),
                ('entering_time', models.CharField(blank=True, max_length=100)),
                ('requested_term', models.TextField(blank=True)),
                ('deposit_bank', models.CharField(blank=True, max_length=100)),
                ('depositor_name', models.CharField(blank=True, max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='location.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
