# Generated by Django 2.1 on 2018-08-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='birth_date',
            new_name='birth_date_of_owner',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='entering_time',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pickup_or_not',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='requested_term',
        ),
        migrations.AddField(
            model_name='reservation',
            name='card_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='card_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='installment_plan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='method_of_payment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(blank=True),
        ),
    ]
