# Generated by Django 2.1 on 2018-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='pickup_or_not',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
