# Generated by Django 2.0.7 on 2018-08-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20180809_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
