# Generated by Django 2.1 on 2018-08-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20180816_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_num',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
