# Generated by Django 2.1 on 2018-08-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('location_no', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('pension_image_thumbnail', models.ImageField(blank=True, upload_to='pension')),
                ('lowest_price', models.IntegerField(blank=True, default=0)),
                ('ypidx', models.IntegerField(blank=True, default=0)),
                ('discount_rate', models.IntegerField(blank=True, default=0)),
                ('address', models.TextField(blank=True)),
                ('check_in', models.TextField(blank=True)),
                ('check_out', models.TextField(blank=True)),
                ('pickup', models.TextField(blank=True)),
                ('room_num', models.IntegerField(blank=True, default=0)),
                ('info', models.TextField(blank=True)),
                ('theme', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, default=0)),
                ('lng', models.FloatField(blank=True, default=0)),
                ('check_in_out_detail', models.TextField(blank=True)),
                ('pickup_detail', models.TextField(blank=True)),
                ('gretting', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PensionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_image', models.ImageField(blank=True, max_length=1000, upload_to='pension')),
            ],
        ),
        migrations.CreateModel(
            name='PensionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('subscriber', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.CharField(blank=True, max_length=100)),
                ('pickup_or_not', models.BooleanField(blank=True, default=True)),
                ('entering_time', models.CharField(blank=True, max_length=100)),
                ('requested_term', models.TextField(blank=True)),
                ('deposit_bank', models.CharField(blank=True, max_length=100)),
                ('depositor_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('structure', models.TextField(blank=True)),
                ('equipments', models.TextField(blank=True)),
                ('info', models.TextField(blank=True)),
                ('size', models.TextField(blank=True)),
                ('normal_num_poeple', models.IntegerField(blank=True, default=0)),
                ('max_num_people', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('extra_charge_head', models.TextField(blank=True)),
                ('extra_charge_adult', models.IntegerField(blank=True, default=0)),
                ('extra_charge_child', models.IntegerField(blank=True, default=0)),
                ('extra_charge_baby', models.IntegerField(blank=True, default=0)),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='location.Pension')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(blank=True, max_length=1000, upload_to='room')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimages', to='location.Room')),
            ],
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('sub_location_no', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='location.Location')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='location.Room'),
        ),
    ]
