# Generated by Django 2.0.7 on 2018-07-26 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pension_image_thumbnail', models.ImageField(blank=True, upload_to='pension')),
                ('lowest_price', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, max_length=100)),
                ('check_in', models.CharField(blank=True, max_length=100)),
                ('check_out', models.CharField(blank=True, max_length=100)),
                ('room_num', models.CharField(blank=True, max_length=100)),
                ('info', models.TextField(blank=True, max_length=100)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('pldx', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('number_of_people', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Pension')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(blank=True, upload_to='room')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Room')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Room'),
        ),
    ]
