# Generated by Django 2.1 on 2018-08-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20180803_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='location.Pension'),
        ),
    ]
