# Generated by Django 2.1 on 2018-08-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20180805_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionimage',
            name='pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensionimages', to='location.Pension'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimages', to='location.Room'),
        ),
    ]
